### PR TITLE
Maintain parties that are part of Cathedral teams.

### LINKED ISSUE #1267: Joining a party (with team members) after joining a team kicks everyone involved out of the team
Steps to reproduce:
Bring two characters to zone 260101.
Use @valuable 694 to enable team creation.
Create a team and join with the second character.
Attempt to form a party with the two characters.

Expected Behavior:
The party is formed and both characters remain in the team.

Observed Behavior:
The party is formed and both characters are kicked out of the team.

Additional note:
May need confirmation that this should apply to team types aside from Cathedral.

### PR DESCRIPTION
**Pull request by TallgeeseHeaven**
1) So long as all party members are part of the same Cathedral team, that team will be maintained.
2) If a team member who is part of a party is removed from the team for any reason, they are removed from the party.

Fixes #1267

### CODE REVIEW

File: server/world/src/CharacterManager.cpp [hunk 1]
```diff
@@ -465,9 +465,25 @@ bool CharacterManager::AddToParty(
...
-  if (success && partyID && login->GetTeamID()) {
-    // When joining a party, all teams must be left
-    TeamLeave(login);
+  if (success && partyID) {
+    // When joining a party, all non-Cathedral teams must be left, so check for
+    // membership in the leader's team (non-Cathedral teams were
+    // broken on party creation)
+    auto teamID = login->GetTeamID();
+    auto leaderTeamID =
+        GetCharacterLogin(GetParty(partyID)->GetLeaderCID())->GetTeamID();
```
Comment (compomega) [inline server/world/src/CharacterManager.cpp:474]: Is GetParty() and GetCharacterLogin() always going to return a valid object? If not, they might need to be checked first.

File: server/world/src/CharacterManager.cpp [hunk 2]
```diff
@@ -465,9 +465,25 @@ bool CharacterManager::AddToParty(
...
+
+    if ((teamID || leaderTeamID) && (teamID != leaderTeamID)) {
+      // New party member is not on the leader's team, revoke all team
+      // memberships of the party members
+      auto partyMemberList = GetParty(partyID)->GetMemberIDsList();
```
Comment (compomega) [inline server/world/src/CharacterManager.cpp:479]: You're grabbing the party again.

File: server/world/src/CharacterManager.cpp [hunk 3]
```diff
@@ -465,9 +465,25 @@ bool CharacterManager::AddToParty(
...
+      for (auto& partyMember : partyMemberList) {
+        auto partyMemberLogin = GetCharacterLogin(partyMember);
+        if (partyMemberLogin) {
+          TeamLeave(partyMemberLogin);
```
Comment (compomega) [inline server/world/src/CharacterManager.cpp:483]: Depending on the context this is run, is it possible for a race condition where someone as added but during this process and missed? Probably not because of how the world is designed.

File: server/world/src/packets/TeamUpdate.cpp [hunk 4]
```diff
@@ -300,8 +300,11 @@ bool Parsers::TeamUpdate::Parse(
       connection->SendPacket(reply);
     } break;
     case InternalPacketAction_t::PACKET_ACTION_GROUP_LEAVE: {
-      // Leave current team
+      // Leave current team and party
       characterManager->TeamLeave(cLogin);
+      if (cLogin->GetPartyID()) {
```
Comment (compomega) [inline server/world/src/packets/TeamUpdate.cpp:305]: This check isn't needed as PartyLeave will simply return if you're not in a party.

File: server/world/src/CharacterManager.cpp [hunk 5]
```diff
@@ -1770,6 +1787,12 @@ void CharacterManager::TeamKick(std::shared_ptr<objects::CharacterLogin> cLogin,
         SendToCharacters(relay, {targetLogin}, cidOffset);
 
         errorCode = (int8_t)TeamErrorCodes_t::SUCCESS;
+
+        // Remove them from their party, as the only way they are in one is if
+        // they're part of a Cathedral team
+        if (targetLogin->GetPartyID()) {
```
Comment (compomega) [inline server/world/src/CharacterManager.cpp:1793]: You can just call PartyLeave without the check.

File: server/world/src/CharacterManager.cpp [hunk 6]
```diff
@@ -463,11 +463,22 @@ bool CharacterManager::AddToParty(
...
     });
-  }
 
-  if (success && partyID && login->GetTeamID()) {
-    // When joining a party, all teams must be left
-    TeamLeave(login);
+    // When joining a party, all non-Cathedral teams must be left, so check
+    // for membership in the leader's team (non-Cathedral teams were broken
+    // on party creation)
+    auto party = partyID ? GetParty(partyID) : 0;
```
Comment (compomega) [inline server/world/src/CharacterManager.cpp:470]: Can you use nullptr instead of 0

File: server/world/src/CharacterManager.cpp [hunk 7]
```diff
@@ -463,11 +463,22 @@ bool CharacterManager::AddToParty(
...
+    auto leader = party ? GetCharacterLogin(party->GetLeaderCID()) : 0;
+    auto leaderTeamID = leader ? leader->GetTeamID() : 0;
+    auto teamID = login->GetTeamID();
+
+    if ((teamID || leaderTeamID) && (teamID != leaderTeamID)) {
+      // New party member is not on the leader's team, revoke all team
+      // memberships of the party members
+      for (auto& partyMember : party->GetMemberIDsList()) {
```
Comment (compomega) [inline server/world/src/CharacterManager.cpp:478]: Is it possible for teamID to be non-zero while leaderTeamID is 0? If so, isn't it possible for party to be null and cause this code to crash? Either the condition is wrong or you may want to check party is valid before doing the loop.

**Review by compomega — APPROVED** [review]
