### PR TITLE
Adjust item useSkill restrictions, misc fixes

### LINKED ISSUE #1145: Admin announcement in chat box
Aeria's GMs had a feature where they could send a message to everyone at once in the chat box, kind of like an @announce Ticker message but in the chat box itself.

Asking for this because temporary ticker messages scroll past and then they're gone. 
Players participating in events often asking "what did that say?" 

(if this is in the wrong section or wrongly formatted or something I apoligize.)

### PR DESCRIPTION
**Pull request by HACKfrost**
Fixes #1145 

Mutex change is possible fix for not very clear crash logs from last release.

### CODE REVIEW

File: server/channel/src/SkillManager.cpp [hunk 1]
```diff
@@ -1077,35 +1078,58 @@ void SkillManager::SendFailure(const std::shared_ptr<ActiveEntityState> source,
...
-            if(!source->CurrentSkillsContains(skillData->GetCommon()->GetID()))
-            {
-                // Ignore special function IDs
-                if(skillData->GetDamage()->GetFunctionID() !=
-                    SVR_CONST.SKILL_CAMEO &&
-                    skillData->GetDamage()->GetFunctionID() !=
-                    SVR_CONST.SKILL_DEMON_FUSION)
-                {
-                    return true;
-                }
```
Comment (HACKfrost) [inline server/channel/src/SkillManager.cpp]: Cameo covered by use skill, fusion not actually needed here at all.
